/**
 * Content Classifiers
 *
 * Classify content as factual, theoretical, or AI-generated.
 */

export type ContentType = 'factual' | 'theoretical' | 'ai_generated' | 'mixed' | 'unknown';

export interface ClassificationResult {
  type: ContentType;
  confidence: number;
  indicators: string[];
  needsDisclaimer: boolean;
}

export function classifyContent(content: string): ClassificationResult {
  const indicators: string[] = [];
  let theoreticalScore = 0;
  let factualScore = 0;
  let aiScore = 0;

  // Check for theoretical indicators
  const theoreticalPatterns = [
    { pattern: /could potentially/i, weight: 2 },
    { pattern: /might enable/i, weight: 2 },
    { pattern: /theoretically/i, weight: 3 },
    { pattern: /conceptual(ly)?/i, weight: 2 },
    { pattern: /proposed/i, weight: 1 },
    { pattern: /envisioned/i, weight: 2 },
    { pattern: /framework/i, weight: 1 },
  ];

  // Check for factual indicators
  const factualPatterns = [
    { pattern: /patent (US|EP|WO)\d+/i, weight: 3 },
    { pattern: /DOI:\s*10\.\d+/i, weight: 3 },
    { pattern: /published in/i, weight: 2 },
    { pattern: /according to/i, weight: 1 },
    { pattern: /demonstrated in \d{4}/i, weight: 2 },
    { pattern: /documented by/i, weight: 2 },
  ];

  // Check for AI-generated indicators
  const aiPatterns = [
    { pattern: /AI[- ]generated/i, weight: 5 },
    { pattern: /generated by/i, weight: 2 },
    { pattern: /automated analysis/i, weight: 2 },
    { pattern: /machine learning/i, weight: 1 },
  ];

  for (const { pattern, weight } of theoreticalPatterns) {
    if (pattern.test(content)) {
      theoreticalScore += weight;
      indicators.push(`Theoretical: ${pattern.source}`);
    }
  }

  for (const { pattern, weight } of factualPatterns) {
    if (pattern.test(content)) {
      factualScore += weight;
      indicators.push(`Factual: ${pattern.source}`);
    }
  }

  for (const { pattern, weight } of aiPatterns) {
    if (pattern.test(content)) {
      aiScore += weight;
      indicators.push(`AI: ${pattern.source}`);
    }
  }

  // Determine content type
  const totalScore = theoreticalScore + factualScore + aiScore;
  let type: ContentType;
  let confidence: number;

  if (aiScore >= 3) {
    type = 'ai_generated';
    confidence = Math.min(0.95, aiScore / 10);
  } else if (theoreticalScore > factualScore * 2) {
    type = 'theoretical';
    confidence = Math.min(0.9, theoreticalScore / (totalScore || 1));
  } else if (factualScore > theoreticalScore * 2) {
    type = 'factual';
    confidence = Math.min(0.9, factualScore / (totalScore || 1));
  } else if (theoreticalScore > 0 || factualScore > 0) {
    type = 'mixed';
    confidence = 0.6;
  } else {
    type = 'unknown';
    confidence = 0.3;
  }

  return {
    type,
    confidence,
    indicators,
    needsDisclaimer: type !== 'factual',
  };
}

export function requiresAiLabel(content: string): boolean {
  const result = classifyContent(content);
  return result.type === 'ai_generated' || result.type === 'theoretical';
}

export function requiresSourceAttribution(content: string): boolean {
  // Any claim about historical facts needs attribution
  const claimPatterns = [
    /Tesla (did|created|invented|discovered)/i,
    /Mallove (wrote|published|discovered)/i,
    /Moray (built|demonstrated|created)/i,
    /research (shows|demonstrates|proves)/i,
    /according to/i,
    /studies (show|indicate|suggest)/i,
  ];

  return claimPatterns.some(p => p.test(content));
}
