/**
 * Verification Report Generators
 *
 * Generate comprehensive reports on source verification status.
 */

import type { VerificationReport, SourceVerificationResult } from '../index';

export interface ReportFormat {
  format: 'json' | 'markdown' | 'html';
}

export function generateMarkdownReport(report: VerificationReport): string {
  const lines: string[] = [
    '# Source Verification Report',
    '',
    `**Generated:** ${report.timestamp.toISOString()}`,
    '',
    '## Summary',
    '',
    `| Metric | Count |`,
    `|--------|-------|`,
    `| Total Sources | ${report.totalSources} |`,
    `| Valid | ${report.validSources} |`,
    `| Invalid | ${report.invalidSources} |`,
    `| Unreachable | ${report.unreachableSources} |`,
    '',
    `**Success Rate:** ${((report.validSources / report.totalSources) * 100).toFixed(1)}%`,
    '',
  ];

  if (report.invalidSources > 0 || report.unreachableSources > 0) {
    lines.push('## Issues Found', '');

    for (const result of report.results) {
      if (!result.isValid) {
        lines.push(`- **${result.url}**`);
        if (result.errorMessage) {
          lines.push(`  - Error: ${result.errorMessage}`);
        }
        if (result.statusCode) {
          lines.push(`  - Status: ${result.statusCode}`);
        }
      }
    }
    lines.push('');
  }

  lines.push(
    '---',
    '*This report was generated by the Chicago Forest Network Source Verifier (Agent 11: Verifier)*',
    '*All sources should link to real, verifiable archives and research databases.*'
  );

  return lines.join('\n');
}

export function generateJsonReport(report: VerificationReport): string {
  return JSON.stringify(report, null, 2);
}

export function generateHtmlReport(report: VerificationReport): string {
  const successRate = ((report.validSources / report.totalSources) * 100).toFixed(1);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Source Verification Report</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin: 20px 0; }
    .stat { background: #f5f5f5; padding: 15px; border-radius: 8px; text-align: center; }
    .stat.valid { background: #d4edda; }
    .stat.invalid { background: #f8d7da; }
    .success-rate { font-size: 2em; font-weight: bold; color: ${parseFloat(successRate) > 90 ? '#28a745' : '#dc3545'}; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 10px; border: 1px solid #ddd; text-align: left; }
    th { background: #f5f5f5; }
    .valid { color: #28a745; }
    .invalid { color: #dc3545; }
  </style>
</head>
<body>
  <h1>Source Verification Report</h1>
  <p><strong>Generated:</strong> ${report.timestamp.toISOString()}</p>

  <div class="summary">
    <div class="stat"><strong>${report.totalSources}</strong><br>Total</div>
    <div class="stat valid"><strong>${report.validSources}</strong><br>Valid</div>
    <div class="stat invalid"><strong>${report.invalidSources}</strong><br>Invalid</div>
    <div class="stat"><strong>${report.unreachableSources}</strong><br>Unreachable</div>
  </div>

  <p class="success-rate">${successRate}% Success Rate</p>

  <h2>Details</h2>
  <table>
    <tr><th>URL</th><th>Status</th><th>Response Time</th></tr>
    ${report.results.map(r => `
    <tr>
      <td>${r.url}</td>
      <td class="${r.isValid ? 'valid' : 'invalid'}">${r.isValid ? 'Valid' : 'Invalid'}</td>
      <td>${r.responseTime ? `${r.responseTime}ms` : 'N/A'}</td>
    </tr>`).join('')}
  </table>

  <footer>
    <p><em>Generated by Chicago Forest Network Source Verifier (Agent 11: Verifier)</em></p>
  </footer>
</body>
</html>`;
}
