apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forest-cp-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: forest-cp-secrets
    creationPolicy: Owner
  data:
    - secretKey: headscale-api-key
      remoteRef:
        key: secret/espo/prod/forest-control-plane
        property: headscale-api-key
