/**
 * Community Metrics
 *
 * Track and analyze community engagement.
 */

export interface CommunityMetrics {
  totalContributors: number;
  activeContributors: number; // Last 30 days
  totalPRs: number;
  mergedPRs: number;
  totalIssues: number;
  openIssues: number;
  closedIssues: number;
  averageTimeToFirstResponse: number; // hours
  averageTimeToClose: number; // hours
}

export interface ContributorStats {
  username: string;
  commits: number;
  prsOpened: number;
  prsMerged: number;
  issuesOpened: number;
  issuesClosed: number;
  reviewsGiven: number;
  firstContribution: Date;
  lastContribution: Date;
}

export function calculateMetrics(
  contributors: ContributorStats[],
  issues: { createdAt: Date; closedAt?: Date; firstResponseAt?: Date }[],
  prs: { createdAt: Date; mergedAt?: Date }[]
): CommunityMetrics {
  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);

  const activeContributors = contributors.filter(
    c => c.lastContribution > thirtyDaysAgo
  ).length;

  const closedIssues = issues.filter(i => i.closedAt);
  const responseTimes = issues
    .filter(i => i.firstResponseAt)
    .map(i => (i.firstResponseAt!.getTime() - i.createdAt.getTime()) / (1000 * 60 * 60));
  const closeTimes = closedIssues
    .map(i => (i.closedAt!.getTime() - i.createdAt.getTime()) / (1000 * 60 * 60));

  return {
    totalContributors: contributors.length,
    activeContributors,
    totalPRs: prs.length,
    mergedPRs: prs.filter(p => p.mergedAt).length,
    totalIssues: issues.length,
    openIssues: issues.filter(i => !i.closedAt).length,
    closedIssues: closedIssues.length,
    averageTimeToFirstResponse: responseTimes.length > 0
      ? responseTimes.reduce((a, b) => a + b, 0) / responseTimes.length
      : 0,
    averageTimeToClose: closeTimes.length > 0
      ? closeTimes.reduce((a, b) => a + b, 0) / closeTimes.length
      : 0,
  };
}

export function generateMetricsReport(metrics: CommunityMetrics): string {
  const mergeRate = metrics.totalPRs > 0
    ? ((metrics.mergedPRs / metrics.totalPRs) * 100).toFixed(1)
    : '0';
  const closeRate = metrics.totalIssues > 0
    ? ((metrics.closedIssues / metrics.totalIssues) * 100).toFixed(1)
    : '0';

  return `
# Community Health Report

## Contributors
- **Total Contributors:** ${metrics.totalContributors}
- **Active (30 days):** ${metrics.activeContributors}

## Pull Requests
- **Total PRs:** ${metrics.totalPRs}
- **Merged PRs:** ${metrics.mergedPRs}
- **Merge Rate:** ${mergeRate}%

## Issues
- **Total Issues:** ${metrics.totalIssues}
- **Open Issues:** ${metrics.openIssues}
- **Closed Issues:** ${metrics.closedIssues}
- **Close Rate:** ${closeRate}%

## Response Times
- **Avg Time to First Response:** ${metrics.averageTimeToFirstResponse.toFixed(1)} hours
- **Avg Time to Close:** ${metrics.averageTimeToClose.toFixed(1)} hours

---
*Generated by Chicago Forest Community Manager (Agent 17: Ambassador)*
  `.trim();
}

export function identifyTopContributors(
  contributors: ContributorStats[],
  limit: number = 10
): ContributorStats[] {
  return [...contributors]
    .sort((a, b) => (b.commits + b.prsMerged * 2) - (a.commits + a.prsMerged * 2))
    .slice(0, limit);
}

export function generateRecognition(contributor: ContributorStats): string[] {
  const recognitions: string[] = [];

  if (contributor.commits >= 100) {
    recognitions.push('🌳 Century Contributor (100+ commits)');
  } else if (contributor.commits >= 50) {
    recognitions.push('🌲 Forest Guardian (50+ commits)');
  } else if (contributor.commits >= 10) {
    recognitions.push('🌱 Growing Contributor (10+ commits)');
  }

  if (contributor.prsMerged >= 20) {
    recognitions.push('🔀 PR Master (20+ merged PRs)');
  }

  if (contributor.reviewsGiven >= 50) {
    recognitions.push('👀 Review Champion (50+ reviews)');
  }

  if (contributor.issuesClosed >= 30) {
    recognitions.push('🔧 Issue Resolver (30+ issues closed)');
  }

  return recognitions;
}
