apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forest-control-plane

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: forest-control-plane
  app.kubernetes.io/part-of: chicago-forest
  app.kubernetes.io/managed-by: kustomize
