/**
 * Tesla Magnifying Transmitter Patents
 *
 * The Magnifying Transmitter was Tesla's most ambitious wireless power device,
 * designed and tested at Colorado Springs and planned for Wardenclyffe.
 *
 * This file documents REAL Tesla patents related to the magnifying transmitter concept.
 * All patent numbers and URLs link to official Google Patents database.
 *
 * HISTORICAL DOCUMENTATION - These are verified historical records.
 */

import type { TeslaPatent } from '../types.js';

/**
 * Electrical Transformer - US593138A
 *
 * The foundational Tesla Coil patent
 * Filed: March 20, 1897
 * Granted: November 2, 1897
 */
export const US593138A: TeslaPatent = {
  patentNumber: 'US593138A',
  title: 'Electrical Transformer',
  filingDate: '1897-03-20',
  grantDate: '1897-11-02',
  googlePatentsUrl: 'https://patents.google.com/patent/US593138A',
  abstract: 'An electrical transformer comprising a primary and secondary coil wound in a specific manner to produce high voltages at high frequencies with minimum energy loss.',
  keyClaims: [
    'Specific coil winding geometry for high-frequency operation',
    'Methods for minimizing capacitance between windings',
    'Resonant operation between primary and secondary',
    'High voltage step-up ratios',
    'Air-core transformer design'
  ],
  relatedPatents: ['US568176A', 'US454622A', 'US1119732A'],
  modernRelevance: 'Foundation for all Tesla coil designs, used in medical equipment, particle accelerators, and high-voltage research.',
  category: 'magnifying-transmitter'
};

/**
 * Apparatus for Producing Electric Currents of High Frequency and Potential - US568176A
 *
 * Describes the resonant transformer principle
 * Filed: June 20, 1896
 * Granted: September 22, 1896
 */
export const US568176A: TeslaPatent = {
  patentNumber: 'US568176A',
  title: 'Apparatus for Producing Electric Currents of High Frequency and Potential',
  filingDate: '1896-06-20',
  grantDate: '1896-09-22',
  googlePatentsUrl: 'https://patents.google.com/patent/US568176A',
  abstract: 'An apparatus for producing electrical currents of very high frequency and high potential using resonant circuits and spark gap oscillators.',
  keyClaims: [
    'Resonant circuit configuration for high-frequency generation',
    'Spark gap as switching mechanism',
    'Capacitor-inductor combinations for frequency control',
    'Methods for achieving high potentials safely'
  ],
  relatedPatents: ['US593138A', 'US454622A'],
  modernRelevance: 'Basis for high-frequency power supplies and resonant converters in modern electronics.',
  category: 'magnifying-transmitter'
};

/**
 * Coil for Electro-Magnets - US512340A
 *
 * Describes the bifilar coil winding method
 * Filed: January 7, 1893
 * Granted: January 9, 1894
 */
export const US512340A: TeslaPatent = {
  patentNumber: 'US512340A',
  title: 'Coil for Electro-Magnets',
  filingDate: '1893-01-07',
  grantDate: '1894-01-09',
  googlePatentsUrl: 'https://patents.google.com/patent/US512340A',
  abstract: 'A coil wound in a specific bifilar arrangement to increase the energy storage capacity while reducing inductance in certain configurations.',
  keyClaims: [
    'Bifilar winding technique',
    'Increased energy storage per unit volume',
    'Reduced self-inductance when desired',
    'Specific applications for high-frequency circuits'
  ],
  relatedPatents: ['US593138A', '568176A'],
  modernRelevance: 'Used in non-inductive precision resistors and special electromagnetic applications.',
  category: 'magnifying-transmitter'
};

/**
 * Apparatus for Producing Electrical Currents of High Frequency - US454622A
 *
 * Early high-frequency apparatus patent
 * Filed: April 25, 1891
 * Granted: June 23, 1891
 */
export const US454622A: TeslaPatent = {
  patentNumber: 'US454622A',
  title: 'System of Electric Lighting',
  filingDate: '1891-04-25',
  grantDate: '1891-06-23',
  googlePatentsUrl: 'https://patents.google.com/patent/US454622A',
  abstract: 'A system of electric lighting using high-frequency currents generated by specific apparatus designs.',
  keyClaims: [
    'High-frequency current generation methods',
    'Single-wire power transmission',
    'Vacuum tube lighting with high-frequency excitation',
    'Efficient conversion of electrical energy to light'
  ],
  relatedPatents: ['US568176A', 'US593138A'],
  modernRelevance: 'Precursor to fluorescent lighting technology and modern high-frequency lighting systems.',
  category: 'magnifying-transmitter'
};

/**
 * Means for Generating Electric Currents - US514168A
 *
 * Describes methods for generating high-frequency currents
 * Filed: August 2, 1893
 * Granted: February 6, 1894
 */
export const US514168A: TeslaPatent = {
  patentNumber: 'US514168A',
  title: 'Means for Generating Electric Currents',
  filingDate: '1893-08-02',
  grantDate: '1894-02-06',
  googlePatentsUrl: 'https://patents.google.com/patent/US514168A',
  abstract: 'Improved means for generating electric currents of high frequency using mechanical and electrical oscillation methods.',
  keyClaims: [
    'Mechanical oscillator designs for current generation',
    'Improved efficiency in high-frequency generation',
    'Combinations of resonant elements for frequency stability',
    'Practical power generation at high frequencies'
  ],
  relatedPatents: ['US568176A', 'US593138A'],
  modernRelevance: 'Influenced development of crystal oscillators and modern frequency generation technology.',
  category: 'magnifying-transmitter'
};

/**
 * All magnifying transmitter related patents
 */
export const MAGNIFYING_TRANSMITTER_PATENTS: TeslaPatent[] = [
  US593138A,
  US568176A,
  US512340A,
  US454622A,
  US514168A
];

/**
 * Get patent by number
 */
export function getMagnifyingPatentByNumber(patentNumber: string): TeslaPatent | undefined {
  return MAGNIFYING_TRANSMITTER_PATENTS.find(p => p.patentNumber === patentNumber);
}

/**
 * Get all magnifying transmitter patent URLs
 */
export function getMagnifyingPatentUrls(): Record<string, string> {
  const urls: Record<string, string> = {};
  for (const patent of MAGNIFYING_TRANSMITTER_PATENTS) {
    urls[patent.patentNumber] = patent.googlePatentsUrl;
  }
  return urls;
}

/**
 * THEORETICAL NOTE - AI GENERATED SPECULATION
 *
 * The "Magnifying Transmitter" term refers to Tesla's concept of an enhanced
 * Tesla coil system capable of wireless power transmission. While Tesla
 * documented experiments at Colorado Springs and planned to build such a
 * system at Wardenclyffe, no fully operational long-distance wireless power
 * transmission system was ever demonstrated.
 *
 * The patents above document the REAL technological foundations Tesla developed.
 * Any claims about operational wireless power transmission systems based on
 * these patents remain theoretical and unproven at large scales.
 */
