"use client"

import { AlertTriangle, Info } from "lucide-react"

export default function Disclaimer() {
  return (
    <div className="bg-yellow-500/10 border-2 border-yellow-500/50 rounded-lg p-6 my-8">
      <div className="flex items-start space-x-3">
        <AlertTriangle className="h-6 w-6 text-yellow-600 flex-shrink-0 mt-0.5" />
        <div className="space-y-2">
          <h3 className="text-lg font-semibold text-yellow-900 dark:text-yellow-400">
            Important Disclaimer: AI-Generated Theoretical Framework
          </h3>
          <p className="text-sm text-yellow-800 dark:text-yellow-300">
            <strong>This entire website and all its content is an AI-generated theoretical framework</strong> created as an 
            exploratory exercise to envision potential pathways to net-zero energy solutions. This is NOT a real, operational 
            network, nor are there any actual plasma forest installations.
          </p>
          <p className="text-sm text-yellow-800 dark:text-yellow-300">
            All technical specifications, protocols, and implementations described here are <strong>speculative interpretations</strong> of 
            historical research by Tesla, Mallove, Moray, and others. This project represents hope and vision for sustainable 
            energy futures, not existing technology or proven solutions.
          </p>
          <p className="text-sm text-yellow-800 dark:text-yellow-300">
            <strong>No claims of working devices or energy generation are being made.</strong> This is a conceptual exploration 
            and should be understood as such. Any real-world implementation would require extensive scientific validation, 
            engineering development, and regulatory approval.
          </p>
          <div className="mt-3 p-3 bg-blue-500/10 rounded border border-blue-500/30">
            <div className="flex items-center space-x-2">
              <Info className="h-5 w-5 text-blue-600 dark:text-blue-400" />
              <p className="text-xs text-blue-800 dark:text-blue-300">
                Generated by AI as a theoretical exercise in sustainable energy visioning. Not investment advice or scientific fact.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}